In [ ]:
# Implementation of matrix product 

In [3]:
## Matrix product 
import numpy as np
a_ndarray = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b_ndarray = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

In [ ]:
# [Problem 1] Matrix product is calculated manually 
## Product of A and B by hand
            # A               B                       C = A X B 
### | a11 a12 a13 |    | b11 b12 b13 |            | c11 c12 c13 |    c11 -----> 1ª row of A and 1ª column of B.  C11= a11*b11 + a12*b21 + a13*b31
### | a21 a22 a23 | X  | b21 b22 b23 |            | c21 c22 c23 |    ............................................................................
### | a31 a32 a33 |    | b31 b32 b33 |            | c31 c32 c33 |    c33 -----> 3ª row of A and 3ª column of B.  C33= a31*b13 + a32*b23 + a33*b33

         
###     | -1,2,3 |       | 0,2, 1 |    
### A = | 4,-5,6 |  B =  | 0,2,-8 |
###     | 7,8,-9 |      | 2,9, -1 |

###     | (-1)*0 + 2*0 + 3*2 , (-1)*2 + 2*2 + 3*9 , (-1)*1 + 2*(-8) + 3*(-1) |    
### C = | 4*0 + (-5)*0 + 6*2 , 4*2 + (-5)*2 + 6*9 , 4*1 + (-5)*(-8) + 6*(-1) | 
###     |7*0 + 8*0 + (-9)*2 , 7*2 + 8*2 + (-9)*9 , 7*1 + 8*(-8) + (-9)*(-1)  |


###     | 0 + 0 + 6 , -2 + 4 + 27 , -1  - 16 - 3 |    
### C = | 0 + 0 + 12 , 8 -10 + 54 ,  4 + 40 -6   | 
###     |0 + 0 + -18 , 14 + 16 -81 , 7 - 64 + 9  |

# The result of the matrix product of A and B == C 
###     | 6 ,  29 , - 20 |    
### C = | 12 , 52 ,  38  | 
###     |-18 , -51 , -48 |



In [7]:
# [ Problem 2] Calculation by NumPy function 
c=np.matmul(a_ndarray,b_ndarray)
print(c)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [12]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [10]:
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [13]:
# [ Problem 3] Implementation of calculation of a certain element 
row_0_A = a_ndarray[0, :]
col_0_B = b_ndarray[:, 0]
element_00 = np.sum(row_0_A * col_0_B)

print(element_00)

6


In [15]:
# [ Problem 4] Creating a function that performs matrix 

def manual_matrix_product(A, B):
    # Check for dimension Compatibility
    # The number of columns in A must equal the number of rows in B
    if A.shape[1] != B.shape[0]:
        prin("Error: The number of columns in the first matrix must equal the number of rows in the second.")
        return None
    # Get the dimensions of the output matrix
    rows_A = A.shape[0]
    cols_B = B.shape[1]
    common_dim = A.shape[1]

    # Create the result matrix filled with zeros
    C = np.zeros((rows_A, cols_B))
    # Iterate through rows of A and columns of B
    for i in range(rows_A):
        for j in range(cols_B):
            # Calculate the dot product of row i of A and column j of B
            sum_of_products = 0
            for k in range(common_dim):
                sum_of_products += A[i, k] * B[k, j]
            # Assign the result to the element C[i, j]
            C[i, j] = sum_of_products
    return C
            
#  Call the function to calculate the product of A and B 
manual_product_AB = manual_matrix_product(a_ndarray, b_ndarray)

if manual_product_AB is not None: 
    print("Result from the manual_product function:")
    print(manual_product_AB)

Result from the manual_product function:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [17]:
# [Problem 5] Judge the input whose calculation is not defined

# Matrices

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])


def manual_matrix_product(A, B):
    # Check if the number of columns in A must equal the number of rows in B
    if A.shape[1] != B.shape[0]:
        print("Error: The number of columns in the first matrix must equal the number of rows in the second.")
        # Return an error None to indicate failure
        return None
    # Get the dimensions of the resulting matrix
    rows_A = A.shape[0]
    cols_B = B.shape[1]
    common_dim = A.shape[1]

    # Create the result matrix store with result
    C = np.zeros((rows_A, cols_B))
    # Perform the matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            sum_of_products = 0
            for k in range(common_dim):
                sum_of_products += A[i, k] * B[k, j]
            C[i, j] = sum_of_products
    return C

# Test the function with matrices D e E 
print("Attempting to calculate the product of D and E:")
result = manual_matrix_product( d_ndarray, e_ndarray)
if result is None: 
    print("Matrix product calculation failed due to incompatible dimensions.")
else:
    print("Result of D x E:")
    print(result)

Attempting to calculate the product of D and E:
Error: The number of columns in the first matrix must equal the number of rows in the second.
Matrix product calculation failed due to incompatible dimensions.


In [18]:
# [Problem 6] Transposition 

# Transpose matrix E using the .T attribute 
e_transposed = e_ndarray.T

# Calculate the matrix product D @ E^T
product = d_ndarray @ e_transposed

print("Matrix D:")
print(d_ndarray)
print("\nTransposed Matrix E (E^T):")
print(e_transposed)
print("\nResult of D @ E^T:")
print(product)



Matrix D:
[[-1  2  3]
 [ 4 -5  6]]

Transposed Matrix E (E^T):
[[-9  6]
 [ 8 -5]
 [ 7  4]]

Result of D @ E^T:
[[ 46  -4]
 [-34  73]]
